name: emais
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  mask_text_input_formatter: ^2.4.0
  animations: ^2.0.7
  dio: ^4.0.6
  flutter_secure_storage: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.5.0
  build_runner: ^2.2.1

flutter:
  uses-material-design: true
  assets:
    - images/logo.png
    - images/fundo.png
